### PR TITLE
Psych compatibility

### PR DESCRIPTION
**Pull request by nevesenin**
Fixes compatibility issues with Psych.safe_load for all psych versions > 2. Also see https://github.com/halostatue/minitar/pull/40.

### CODE REVIEW

**Review by halostatue — CHANGES_REQUESTED** [review]
The `.gemspec` file should not be included in the PR; it is regenerated by `hoe` and committed as part of a release.

**Comment by halostatue** [comment]
Otherwise this looks good.

**Comment by nevesenin** [comment]
> The `.gemspec` file should not be included in the PR; it is regenerated by `hoe` and committed as part of a release.
Ah, ok. Just wanted to add some kind of test and saw this: https://github.com/raggi/hoe-gemspec2/blob/7f34c90a1a4fcb3dc01d916e3c6c7618f3766270/Rakefile#L5
Will remove it.

**Review by halostatue — APPROVED** [review]

**Comment by halostatue** [comment]
I can merge this, but I’d like to give @raggi a day or two to pipe in on this before I do.

**Comment by nevesenin** [comment]
Great! Thanks!

**Pull request merged**
